---
language: python
python:
  - "3.6"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
install:
  - pip install -r requirements.txt
  - pip install pylint
  # Test the `setup.py` usage by installing the local package.
  - pip install .
script:
  - pylint cgc/cgc.py
  - ./tests.py
